services:
  telegram_bot:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      # Force l'affichage virtuel pour certaines libs (optionnel mais utile)
      - DISPLAY=:99
    build:
      # Le contexte est le dossier parent (le root du projet)
      context: ..
      # Le Dockerfile est dans le dossier deploy (relatif au contexte)
      dockerfile: deploy/Dockerfile
    container_name: telegram_bot
    shm_size: '2gb'
    restart: always

    # Le .env file est dans config (relatif au contexte)
    env_file:
      - ../config/.env
    volumes:
      # Les volumes sont mapp├®s depuis le root (relatif au contexte)
      - ../storage:/app/storage
      - ../logs:/app/logs
      - ../project:/app/profile_data # <-- Elle pointe vers ton dossier
      - ../my_playwright_profile_1:/app/my_playwright_profile_1
      - ../my_playwright_profile_2:/app/my_playwright_profile_2
      - ../my_playwright_profile_3:/app/my_playwright_profile_3
      - ../my_playwright_profile_4:/app/my_playwright_profile_4
      - ../my_playwright_profile_5:/app/my_playwright_profile_5
      - ../screenshots:/app/screenshots
    working_dir: /app
